services:
  web:
    build: .
    container_name: triloka_search
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - chroma_data:/app/chroma_off
    environment:
      - DEV=${DEV:-false}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-gemini}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_API_URL=${NODE_API_URL:-http://triloka-backend:3000}
      - PORT_KEY_API_KEY=${PORT_KEY_API_KEY}
      - PORT_KEY_ID=${PORT_KEY_ID}
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_TELEMETRY=False
    env_file:
      - .env
    command: >
      sh -c "
      if [ \"$$DEV\" = \"true\" ]; then
        uvicorn api:app --host 0.0.0.0 --port 8003 --reload;
      else
        uvicorn api:app --host 0.0.0.0 --port 8003;
      fi
      "
    restart: unless-stopped

volumes:
  chroma_data:
